### ISSUE TITLE
 No module named 'additive_bo'

### ISSUE THREAD

**Issue by iterateccvoelker** [doncamilom/BOLLaMa#1]
Hi,

this project looks extremly interesting. Unfortunately, I cannot run it via  "python app.py"

I keep getting this error: 

_No module named 'additive_bo'_

I am also not able to install it via pip install. Is this a local package? Thank you so much in advance for some brief help.

Best, 

Christoph

**Comment by doncamilom** [comment]
Hi Christoph,

we've solved this issue by updating to CHAOS which replaces additive_bo. 

Thanks for your comment :)
